// src/vue/App.vue
<template>
  <h1>Vue App</h1>
  <p>Count is {{ count }}</p>
  <button v-on:click="increase">Increase</button>
  <span style="padding: 8px;"></span>
  <button v-on:click="decrease">Decrease</button>
</template>

<style scoped>

</style>

<style scoped>
</style>

<script>
export default {
  data() {
    console.log('Source map test');
    return {
      count: 0
    }
  },
  methods: {
    increase() {
      this.count++;
    },
    decrease() {
      this.count--;
    }
  }
}
</script>

// src/react/App.jsx
import * as React from 'react';

export const App = () => {
    const [count, setCount] = React.useState(0);

    console.log('Source map test');

    return (
        <div>
            <h1>React App</h1>
            <p>Count is {count}</p>
            {/* <p>New content</p> */}
            <button onClick={() => setCount(count + 10)}>Increase+</button>
            <span style={{width: 10, display: 'inline-block'}}></span>
            <button onClick={() => setCount(count - 10)}>Decrease-</button>
        </div>
    )
}
